"""Declarative base, deterministic constraint naming and shared mixins.

Every constraint name is generated by the ``NAMING_CONVENTION`` below rather
than left to the database. Two consequences, both of which matter for a project
whose schema is versioned by Alembic:

* a constraint that has a name in the models has the *same* name in the
  migration, so ``alembic downgrade``/``upgrade`` round-trips cleanly on SQLite
  (which rewrites whole tables to drop a constraint);
* the model/metadata drift test can compare constraint names rather than
  guessing what the database called something.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from rfq_agent.observability.ids import utc_now
from rfq_agent.persistence.types import UtcDateTime

__all__ = [
    "NAMING_CONVENTION",
    "Base",
    "TimestampMixin",
]

#: Deterministic names for every index, constraint and foreign key.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for every persistence model.

    The persistence layer is deliberately *separate* from the domain layer:
    domain models are frozen pydantic value objects that never touch a session,
    persistence models are mutable SQLAlchemy rows that never perform business
    arithmetic. Mapping between them is done explicitly in the repositories
    (Phase 1C), which keeps a schema change from silently altering a domain
    contract and vice versa.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds ``created_at`` / ``updated_at`` to a table.

    Timestamps are generated in Python (``utc_now``) rather than by a server-side
    default: SQLite's ``CURRENT_TIMESTAMP`` has second resolution and no
    timezone, so two events in the same second would be indistinguishable in an
    audit trail.
    """

    created_at: Mapped[datetime] = mapped_column(UtcDateTime, default=utc_now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        UtcDateTime, default=utc_now, onupdate=utc_now, nullable=False
    )
